'use client';

import { useCallback } from 'react';
import { useDemo } from '@/lib/DemoContext';
import HelpTooltip from './HelpTooltip';
import { ChevronLeft, FileText, Printer, Download, PartyPopper, TrendingUp } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ResultsPage() {
  const { state, setCurrentStep, calculateDistribution } = useDemo();

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(amount);
  };

  const totalDistributed = state.distributionResults.reduce(
    (sum, result) => sum + result.receivedAmount,
    0
  );

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = useCallback(() => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(249, 115, 22); // Orange accent
    doc.rect(0, 0, 220, 35, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Tip Share Pro', 14, 18);

    doc.setFontSize(10);
    doc.text('Sharing The Customers Appreciation', 14, 26);

    // Title
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(18);
    doc.text('Tip Pool Distribution Report', 14, 50);

    // Date and summary
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    const currentDate = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.text(`Generated: ${currentDate}`, 14, 58);
    doc.text(`Pay Period: ${state.settings.payPeriodType}`, 14, 64);
    doc.text(`Total Pool: ${formatCurrency(state.projectedPool)}`, 14, 70);
    doc.text(`Contribution Rate: ${state.settings.contributionRate}%`, 14, 76);

    // Table data - NOTE: Wage column is intentionally excluded for confidentiality
    const tableData = state.distributionResults.map((result) => [
      result.employeeName,
      result.jobCategory,
      result.hoursWorked.toString(),
      // Hourly rate intentionally NOT included for confidentiality
      `${result.sharePercentage.toFixed(2)}%`,
      formatCurrency(result.shareAmount),
      formatCurrency(result.receivedAmount),
    ]);

    // Add totals row
    const totalHours = state.distributionResults.reduce((sum, r) => sum + r.hoursWorked, 0);
    const totalShare = state.distributionResults.reduce((sum, r) => sum + r.shareAmount, 0);
    const totalReceived = state.distributionResults.reduce((sum, r) => sum + r.receivedAmount, 0);

    tableData.push([
      'TOTAL',
      '',
      totalHours.toString(),
      '100.00%',
      formatCurrency(totalShare),
      formatCurrency(totalReceived),
    ]);

    autoTable(doc, {
      startY: 85,
      head: [['Employee', 'Role', 'Hours', 'Share %', 'Share', 'Received']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 30 },
        2: { cellWidth: 20, halign: 'right' },
        3: { cellWidth: 25, halign: 'right' },
        4: { cellWidth: 30, halign: 'right' },
        5: { cellWidth: 30, halign: 'right' },
      },
      didParseCell: (data) => {
        // Style the totals row
        if (data.row.index === tableData.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [249, 115, 22];
          data.cell.styles.textColor = [255, 255, 255];
        }
      },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(
      'This report was generated by Tip Share Pro. Wage information excluded for confidentiality.',
      14,
      pageHeight - 20
    );
    doc.text('www.tipsharepro.com', 14, pageHeight - 14);

    // Save the PDF
    doc.save(`tip-distribution-${new Date().toISOString().split('T')[0]}.pdf`);
  }, [state.distributionResults, state.projectedPool, state.settings, formatCurrency]);

  // Recalculate if needed
  if (state.distributionResults.length === 0 && state.employees.length > 0) {
    calculateDistribution();
  }

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Celebration Header */}
      <div className="bg-gradient-to-r from-[var(--accent)] to-[var(--accent-hover)] rounded-xl p-8 text-white shadow-lg text-center">
        <div className="flex items-center justify-center gap-3 mb-4">
          <PartyPopper size={32} />
          <h1 className="text-3xl font-bold">Distribution Complete!</h1>
          <PartyPopper size={32} />
        </div>
        <p className="text-lg opacity-90 mb-4">Sharing The Customers Appreciation</p>
        <div className="flex items-center justify-center gap-8 mt-6">
          <div className="text-center">
            <div className="text-4xl font-bold">{formatCurrency(state.projectedPool)}</div>
            <div className="text-sm opacity-75">Total Pool</div>
          </div>
          <div className="w-px h-16 bg-white/30"></div>
          <div className="text-center">
            <div className="text-4xl font-bold">{state.distributionResults.length}</div>
            <div className="text-sm opacity-75">Team Members</div>
          </div>
          <div className="w-px h-16 bg-white/30"></div>
          <div className="text-center">
            <div className="text-4xl font-bold flex items-center gap-2">
              <TrendingUp size={28} />
              {formatCurrency(totalDistributed / state.distributionResults.length)}
            </div>
            <div className="text-sm opacity-75">Avg. Per Person</div>
          </div>
        </div>
      </div>

      {/* Distribution Table */}
      <div className="bg-[var(--background-secondary)] rounded-xl p-6 border border-[var(--border)]">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-semibold text-white">Distribution Details</h2>
            <HelpTooltip text="Each employee's share is calculated based on hours worked, pay rate, and job category weight. The calculation formula ensures fair distribution based on contribution and experience." />
          </div>
          <div className="flex gap-3 no-print">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-[var(--background-tertiary)] text-white rounded-lg hover:bg-[var(--border)] transition-colors flex items-center gap-2"
            >
              <Printer size={18} />
              Print
            </button>
            <button
              onClick={handleExportPDF}
              className="px-4 py-2 bg-[var(--accent)] text-white rounded-lg hover:bg-[var(--accent-hover)] transition-colors flex items-center gap-2"
            >
              <Download size={18} />
              Export PDF
            </button>
          </div>
        </div>

        {/* Print Header - Only visible when printing */}
        <div className="print-only mb-8 text-center border-b-2 border-[var(--accent)] pb-4">
          <h1 className="text-2xl font-bold">Tip Share Pro</h1>
          <p className="text-lg">Tip Pool Distribution Report</p>
          <p className="text-sm text-gray-600">
            Generated: {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Table */}
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b-2 border-[var(--border)]">
                <th className="text-left py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Employee
                </th>
                <th className="text-left py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Role
                </th>
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Hours
                </th>
                {/* Wage column - hidden in print/PDF */}
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)] wage-column no-print">
                  Rate
                </th>
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Weight
                </th>
                {/* IMPORTANT: Basis column is NEVER shown - proprietary algorithm */}
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Share %
                </th>
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--foreground-muted)]">
                  Share
                </th>
                <th className="text-right py-3 px-4 text-sm font-semibold text-[var(--success)]">
                  Received
                </th>
              </tr>
            </thead>
            <tbody>
              {state.distributionResults.map((result, index) => (
                <tr
                  key={result.employeeId}
                  className={`border-b border-[var(--border)] hover:bg-[var(--background-tertiary)] transition-colors ${
                    index % 2 === 0 ? 'bg-[var(--background-tertiary)]/30' : ''
                  }`}
                >
                  <td className="py-4 px-4 font-medium text-white">{result.employeeName}</td>
                  <td className="py-4 px-4">
                    <span className="px-2 py-1 bg-[var(--accent-muted)] text-[var(--accent)] rounded-md text-sm">
                      {result.jobCategory}
                    </span>
                  </td>
                  <td className="py-4 px-4 text-right text-[var(--foreground-muted)] tabular-nums">
                    {result.hoursWorked}
                  </td>
                  {/* Wage column - hidden in print/PDF */}
                  <td className="py-4 px-4 text-right text-[var(--foreground-muted)] tabular-nums wage-column no-print">
                    {formatCurrency(result.hourlyRate)}
                  </td>
                  <td className="py-4 px-4 text-right text-[var(--foreground-muted)] tabular-nums">
                    ×{result.variableWeight.toFixed(2)}
                  </td>
                  <td className="py-4 px-4 text-right text-[var(--foreground-muted)] tabular-nums">
                    {result.sharePercentage.toFixed(2)}%
                  </td>
                  <td className="py-4 px-4 text-right text-white tabular-nums">
                    {formatCurrency(result.shareAmount)}
                  </td>
                  <td className="py-4 px-4 text-right font-bold text-[var(--success)] tabular-nums">
                    {formatCurrency(result.receivedAmount)}
                  </td>
                </tr>
              ))}

              {/* Totals Row */}
              <tr className="bg-[var(--accent)] text-white font-bold">
                <td className="py-4 px-4">TOTAL</td>
                <td className="py-4 px-4"></td>
                <td className="py-4 px-4 text-right tabular-nums">
                  {state.distributionResults.reduce((sum, r) => sum + r.hoursWorked, 0)}
                </td>
                <td className="py-4 px-4 text-right wage-column no-print">—</td>
                <td className="py-4 px-4 text-right">—</td>
                <td className="py-4 px-4 text-right tabular-nums">100.00%</td>
                <td className="py-4 px-4 text-right tabular-nums">
                  {formatCurrency(state.distributionResults.reduce((sum, r) => sum + r.shareAmount, 0))}
                </td>
                <td className="py-4 px-4 text-right tabular-nums">
                  {formatCurrency(totalDistributed)}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* Pool Matching Verification */}
        <div className="mt-6 p-4 bg-[var(--success-bg)] rounded-lg border border-[var(--success)]/20">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-[var(--success)] rounded-full flex items-center justify-center text-white">
              ✓
            </div>
            <div>
              <p className="font-semibold text-[var(--success)]">Pool Total Verified</p>
              <p className="text-sm text-[var(--foreground-muted)]">
                Distribution total ({formatCurrency(totalDistributed)}) matches pool amount exactly.
              </p>
            </div>
          </div>
        </div>

        {/* Calculation Note */}
        <div className="mt-4 p-4 bg-[var(--background-tertiary)] rounded-lg">
          <p className="text-sm text-[var(--foreground-muted)]">
            <strong className="text-white">How shares are calculated:</strong> Each team member&apos;s share is determined by their hours worked, experience level (reflected in hourly rate), and their job category&apos;s impact on customer satisfaction. This creates a fair, weighted distribution that rewards both effort and customer impact.
          </p>
        </div>
      </div>

      {/* Action Cards */}
      <div className="grid md:grid-cols-2 gap-6 no-print">
        <div className="bg-[var(--background-secondary)] rounded-xl p-6 border border-[var(--border)]">
          <FileText size={24} className="text-[var(--accent)] mb-4" />
          <h3 className="text-lg font-semibold text-white mb-2">Print Report</h3>
          <p className="text-sm text-[var(--foreground-muted)] mb-4">
            Generate a printable version of this distribution. Wage information is automatically hidden for confidentiality.
          </p>
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-[var(--background-tertiary)] text-white rounded-lg hover:bg-[var(--border)] transition-colors"
          >
            Print Report
          </button>
        </div>

        <div className="bg-[var(--background-secondary)] rounded-xl p-6 border border-[var(--border)]">
          <Download size={24} className="text-[var(--accent)] mb-4" />
          <h3 className="text-lg font-semibold text-white mb-2">Export PDF</h3>
          <p className="text-sm text-[var(--foreground-muted)] mb-4">
            Download a professional PDF report with TipSharePro branding. Perfect for record-keeping.
          </p>
          <button
            onClick={handleExportPDF}
            className="px-4 py-2 bg-[var(--accent)] text-white rounded-lg hover:bg-[var(--accent-hover)] transition-colors"
          >
            Download PDF
          </button>
        </div>
      </div>

      {/* Navigation */}
      <div className="flex justify-between pt-4 no-print">
        <button
          onClick={() => setCurrentStep(2)}
          className="px-6 py-3 bg-[var(--background-tertiary)] text-white rounded-lg hover:bg-[var(--border)] transition-colors font-medium flex items-center gap-2"
        >
          <ChevronLeft size={20} />
          Back to Data Entry
        </button>
        <button
          onClick={() => setCurrentStep(1)}
          className="px-6 py-3 bg-[var(--accent-muted)] text-[var(--accent)] rounded-lg hover:bg-[var(--accent)] hover:text-white transition-colors font-medium"
        >
          Start New Calculation
        </button>
      </div>
    </div>
  );
}
