'use client';

import { useCallback } from 'react';
import { useDemo } from '@/lib/DemoContext';
import HelpTooltip from './HelpTooltip';
import { ChevronLeft, FileText, Printer, Download, PartyPopper, TrendingUp, CheckCircle } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ResultsPage() {
  const { state, setCurrentStep, calculateDistribution } = useDemo();

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(amount);
  };

  const totalDistributed = state.distributionResults.reduce(
    (sum, result) => sum + result.receivedAmount,
    0
  );

  const handlePrint = () => {
    window.print();
  };

  const handleExportPDF = useCallback(() => {
    const doc = new jsPDF();

    // Header with Bold design system colors
    doc.setFillColor(26, 75, 124); // Navy #1A4B7C
    doc.rect(0, 0, 220, 35, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Tip Share Pro', 14, 18);

    doc.setFontSize(10);
    doc.text('Sharing The Customers Appreciation', 14, 26);

    // Title
    doc.setTextColor(41, 37, 36); // Charcoal
    doc.setFontSize(18);
    doc.text('Tip Pool Distribution Report', 14, 50);

    // Date and summary
    doc.setFontSize(10);
    doc.setTextColor(120, 113, 108); // Muted text
    const currentDate = new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.text(`Generated: ${currentDate}`, 14, 58);
    doc.text(`Pay Period: ${state.settings.payPeriodType}`, 14, 64);
    doc.text(`Total Pool: ${formatCurrency(state.projectedPool)}`, 14, 70);
    doc.text(`Contribution Rate: ${state.settings.contributionRate}%`, 14, 76);

    // Table data - NOTE: Wage column is intentionally excluded for confidentiality
    const tableData = state.distributionResults.map((result) => [
      result.employeeName,
      result.jobCategory,
      result.hoursWorked.toString(),
      // Hourly rate intentionally NOT included for confidentiality
      `${result.sharePercentage.toFixed(2)}%`,
      formatCurrency(result.shareAmount),
      formatCurrency(result.receivedAmount),
    ]);

    // Add totals row
    const totalHours = state.distributionResults.reduce((sum, r) => sum + r.hoursWorked, 0);
    const totalShare = state.distributionResults.reduce((sum, r) => sum + r.shareAmount, 0);
    const totalReceived = state.distributionResults.reduce((sum, r) => sum + r.receivedAmount, 0);

    tableData.push([
      'TOTAL',
      '',
      totalHours.toString(),
      '100.00%',
      formatCurrency(totalShare),
      formatCurrency(totalReceived),
    ]);

    autoTable(doc, {
      startY: 85,
      head: [['Employee', 'Role', 'Hours', 'Share %', 'Share', 'Received']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [26, 75, 124], // Navy
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      alternateRowStyles: {
        fillColor: [245, 245, 244], // Stone
      },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 30 },
        2: { cellWidth: 20, halign: 'right' },
        3: { cellWidth: 25, halign: 'right' },
        4: { cellWidth: 30, halign: 'right' },
        5: { cellWidth: 30, halign: 'right' },
      },
      didParseCell: (data) => {
        // Style the totals row
        if (data.row.index === tableData.length - 1) {
          data.cell.styles.fontStyle = 'bold';
          data.cell.styles.fillColor = [232, 93, 4]; // Primary Orange
          data.cell.styles.textColor = [255, 255, 255];
        }
      },
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(120, 113, 108);
    doc.text(
      'This report was generated by Tip Share Pro. Wage information excluded for confidentiality.',
      14,
      pageHeight - 20
    );
    doc.text('www.tipsharepro.com', 14, pageHeight - 14);

    // Save the PDF
    doc.save(`tip-distribution-${new Date().toISOString().split('T')[0]}.pdf`);
  }, [state.distributionResults, state.projectedPool, state.settings]);

  // Recalculate if needed
  if (state.distributionResults.length === 0 && state.employees.length > 0) {
    calculateDistribution();
  }

  // Get badge class for job category
  const getBadgeClass = (category: string) => {
    const lower = category.toLowerCase();
    if (lower.includes('server')) return 'badge-server';
    if (lower.includes('bartender')) return 'badge-bartender';
    if (lower.includes('cook')) return 'badge-cook';
    if (lower.includes('busser')) return 'badge-busser';
    if (lower.includes('host')) return 'badge-host';
    return 'badge-server';
  };

  return (
    <div className="content-container">
      {/* Celebration Header */}
      <div className="card card-hero card-celebration">
        <div className="celebration-header">
          <PartyPopper size={32} />
          <h1 className="celebration-title">Distribution Complete!</h1>
          <PartyPopper size={32} />
        </div>
        <p className="celebration-subtitle">Sharing The Customers Appreciation</p>
        <div className="celebration-stats">
          <div className="celebration-stat">
            <div className="celebration-value">{formatCurrency(state.projectedPool)}</div>
            <div className="celebration-label">Total Pool</div>
          </div>
          <div className="celebration-divider"></div>
          <div className="celebration-stat">
            <div className="celebration-value">{state.distributionResults.length}</div>
            <div className="celebration-label">Team Members</div>
          </div>
          <div className="celebration-divider"></div>
          <div className="celebration-stat">
            <div className="celebration-value">
              <TrendingUp size={28} className="inline mr-2" />
              {formatCurrency(totalDistributed / (state.distributionResults.length || 1))}
            </div>
            <div className="celebration-label">Avg. Per Person</div>
          </div>
        </div>
      </div>

      {/* Distribution Table */}
      <div className="card">
        <div className="card-header">
          <div className="flex items-center gap-2">
            <h2 className="card-title">Distribution Details</h2>
            <HelpTooltip text="Each employee's share is calculated based on hours worked, pay rate, and job category weight. The calculation formula ensures fair distribution based on contribution and experience." />
          </div>
          <div className="card-actions no-print">
            <button onClick={handlePrint} className="btn btn-ghost">
              <Printer size={18} />
              Print
            </button>
            <button onClick={handleExportPDF} className="btn btn-primary">
              <Download size={18} />
              Export PDF
            </button>
          </div>
        </div>

        {/* Print Header - Only visible when printing */}
        <div className="print-only print-header">
          <h1>Tip Share Pro</h1>
          <p>Tip Pool Distribution Report</p>
          <p className="print-date">
            Generated: {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        {/* Table */}
        <div className="table-wrapper">
          <table className="table table-distribution" role="grid" aria-label="Tip Distribution Report">
            <thead>
              <tr>
                <th scope="col">Employee</th>
                <th scope="col">Role</th>
                <th scope="col" className="text-right">Hours</th>
                {/* Wage column - hidden in print/PDF */}
                <th scope="col" className="text-right hide-on-print wage-column">Rate</th>
                <th scope="col" className="text-right">Weight</th>
                {/* IMPORTANT: Basis column is NEVER shown - proprietary algorithm */}
                <th scope="col" className="text-right">Share %</th>
                <th scope="col" className="text-right">Share</th>
                <th scope="col" className="text-right">Received</th>
              </tr>
            </thead>
            <tbody>
              {state.distributionResults.map((result) => (
                <tr key={result.employeeId}>
                  <td className="font-medium">{result.employeeName}</td>
                  <td>
                    <span className={`badge ${getBadgeClass(result.jobCategory)}`}>
                      {result.jobCategory}
                    </span>
                  </td>
                  <td className="text-right text-mono">{result.hoursWorked}</td>
                  {/* Wage column - hidden in print/PDF */}
                  <td className="text-right text-mono hide-on-print wage-column">
                    {formatCurrency(result.hourlyRate)}
                  </td>
                  <td className="text-right text-mono">x{result.variableWeight.toFixed(2)}</td>
                  <td className="text-right text-mono">{result.sharePercentage.toFixed(2)}%</td>
                  <td className="text-right text-mono">{formatCurrency(result.shareAmount)}</td>
                  <td className="text-right text-mono font-bold text-success">
                    {formatCurrency(result.receivedAmount)}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="table-total">
                <td>TOTAL</td>
                <td></td>
                <td className="text-right text-mono">
                  {state.distributionResults.reduce((sum, r) => sum + r.hoursWorked, 0)}
                </td>
                <td className="text-right hide-on-print wage-column">-</td>
                <td className="text-right">-</td>
                <td className="text-right text-mono">100.00%</td>
                <td className="text-right text-mono">
                  {formatCurrency(state.distributionResults.reduce((sum, r) => sum + r.shareAmount, 0))}
                </td>
                <td className="text-right text-mono font-bold">
                  {formatCurrency(totalDistributed)}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>

        {/* Pool Matching Verification */}
        <div className="verification-banner">
          <CheckCircle size={24} className="verification-icon" />
          <div className="verification-content">
            <p className="verification-title">Pool Total Verified</p>
            <p className="verification-text">
              Distribution total ({formatCurrency(totalDistributed)}) matches pool amount exactly.
            </p>
          </div>
        </div>

        {/* Calculation Note */}
        <div className="info-box">
          <p>
            <strong>How shares are calculated:</strong> Each team member&apos;s share is determined by their hours worked, experience level (reflected in hourly rate), and their job category&apos;s impact on customer satisfaction. This creates a fair, weighted distribution that rewards both effort and customer impact.
          </p>
        </div>
      </div>

      {/* Action Cards */}
      <div className="action-cards no-print">
        <div className="card action-card">
          <FileText size={24} className="action-icon" />
          <h3 className="action-title">Print Report</h3>
          <p className="action-description">
            Generate a printable version of this distribution. Wage information is automatically hidden for confidentiality.
          </p>
          <button onClick={handlePrint} className="btn btn-ghost">
            Print Report
          </button>
        </div>

        <div className="card action-card">
          <Download size={24} className="action-icon" />
          <h3 className="action-title">Export PDF</h3>
          <p className="action-description">
            Download a professional PDF report with TipSharePro branding. Perfect for record-keeping.
          </p>
          <button onClick={handleExportPDF} className="btn btn-primary">
            Download PDF
          </button>
        </div>
      </div>

      {/* Navigation */}
      <div className="nav-buttons no-print">
        <button
          onClick={() => setCurrentStep(2)}
          className="btn btn-ghost"
        >
          <ChevronLeft size={20} />
          Back to Data Entry
        </button>
        <button
          onClick={() => setCurrentStep(1)}
          className="btn btn-secondary"
        >
          Start New Calculation
        </button>
      </div>
    </div>
  );
}
